### ISSUE TITLE
Running with CPU/ AutoCPD package

### ISSUE THREAD

**Issue by ghost** [Jieli12/AutoCPD#2]
Hi, Interesting research topic! I wanted to ask if it is possible to train with A CPU ? will that take days to train? when AutoCPD will be released as package so I can test it out and also I would appreciate if you can provide notebook demo with it

**Comment by Jieli12** [comment]
Hi, thank you for showing an interest in this project. Of course, the model can be trained on a pure CPU server. However, I guess it will take one day or several days to complete one set of hyper-parameters for the deep neural network. I strongly recommend that you should try to run the script on a GPU server.

We are working on the Python package AutoCPD,  it will be available online (PyPi) soon.  We can provide some demos to demonstrate how to use this package.

**Comment by Jieli12** [comment]
Hi, I have published the package on [PyPi index](https://pypi.org/project/autocpd/). There are also 3 Python scripts for different scenarios in test folder. Please see the usage in README.md.
